packages:
  - "packages/*"
allowBuilds:
  "'": true
  ',': true
  '-': true
  '[': true
  ']': true
  b: true
  bcrypt: true
  d: true
  e: true
  esbuild: false
  g: true
  i: true
  l: true
  m: true
  mongodb-memory-server: false
  n: true
  o: true
  r: true
  s: true
  u: true
  v: true
  y: true
