/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Result of checking all achievements. */
export interface AchievementCheck {
  newlyUnlocked: Array<AchievementStatus>
  allStatuses: Array<AchievementStatus>
}

/** Definition of an achievement. */
export interface AchievementDef {
  slug: string
  name: string
  description: string
  requiredCount: number
}

/** Result of checking a single achievement. */
export interface AchievementStatus {
  slug: string
  name: string
  unlocked: boolean
  progress: number
}

/** Types of developer activities that earn XP. */
export declare const enum ActivityType {
  Commit = 'Commit',
  PullRequest = 'PullRequest',
  Review = 'Review',
  Issue = 'Issue',
  Merge = 'Merge'
}

/** Calculate global platform statistics from aggregated values. */
export declare function calculateGlobalStats(userCount: number, totalXp: number, totalActivities: number, teamCount: number, levelSum: number): GlobalStats

/**
 * Calculate level from total XP.
 * Formula: level = floor(0.1 * `sqrt(total_xp)`) + 1
 */
export declare function calculateLevel(totalXp: number): LevelInfo

/** Calculate aggregated statistics for a team from member XP data. */
export declare function calculateTeamStats(memberXps: Array<number>, weeklyXps: Array<number>): TeamStats

/** Calculate XP earned for an activity, applying streak multiplier. */
export declare function calculateXp(activityType: ActivityType, streakMultiplier: number): XpResult

/**
 * Check which achievements are unlocked given definitions and current counts.
 *
 * `current_counts` is a parallel array to `definitions` with the user's current
 * progress count for each achievement.
 */
export declare function checkAchievements(definitions: Array<AchievementDef>, currentCounts: Array<number>): AchievementCheck

/**
 * Evaluate streak based on activity timestamps.
 *
 * Rules:
 * - Same day -> unchanged
 * - Yesterday -> streak + 1
 * - Gap > 1 day -> reset to 1
 * - No previous activity (`last_activity_ms` < 0) -> start at 1
 */
export declare function evaluateStreak(lastActivityMs: number, currentMs: number, currentStreak: number, longestStreak: number): StreakResult

/** Global platform statistics (admin). */
export interface GlobalStats {
  totalUsers: number
  totalXp: number
  totalActivities: number
  totalTeams: number
  averageLevel: number
}

/** An entry in the leaderboard. */
export interface LeaderboardEntry {
  userId: string
  username: string
  xp: number
  level: number
  currentStreak: number
  rank: number
}

/** Information about the user's current level. */
export interface LevelInfo {
  level: number
  totalXp: number
  xpForCurrentLevel: number
  xpForNextLevel: number
}

/**
 * Sort leaderboard entries by XP descending, tie-break by streak descending.
 * Assigns rank starting from 1.
 */
export declare function sortLeaderboard(entries: Array<LeaderboardEntry>): Array<LeaderboardEntry>

/** Result of a streak evaluation. */
export interface StreakResult {
  currentStreak: number
  longestStreak: number
  multiplier: number
}

/** Aggregated statistics for a team. */
export interface TeamStats {
  totalXp: number
  memberCount: number
  averageXp: number
  weeklyXp: number
}

/** Result of an XP calculation. */
export interface XpResult {
  baseXp: number
  multiplier: number
  totalXp: number
}
